services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/database/database.sqlite
      - INIT_SQL_PATH=/app/database/init.sql